language: go

go:
  - 1
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.9.2

install: 
  - mkdir -p $GOPATH/src/github.com/goncharovnikita
  - ln -s $GOPATH/src/github.com/goncharovnikita/go
  - ./install-deps.sh

script: go test ./...
